#DEFINED ERRORS
NO_ERROR         = 'OK'
RELOAD_NOT_FOUND = 'ERROR01'
MISSING_VARS     = 'ERROR02'
NO_COMMAND_FOUND = 'ERROR03'
NO_VARS          = 'ERROR04'
COMMAND_NOT_FOUND  = 'ERROR05'
PARSING_COMMAND_ERROR = 'ERROR06'
INVALID_CALL		  = 'ERROR07'